# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'leaf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sCO2blade_designer(object):
    def setupUi(self, sCO2blade_designer):
        sCO2blade_designer.setObjectName("sCO2blade_designer")
        sCO2blade_designer.resize(1085, 737)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        sCO2blade_designer.setWindowIcon(icon)
        sCO2blade_designer.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(sCO2blade_designer)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(225, 0))
        self.frame.setMaximumSize(QtCore.QSize(225, 16777215))
        self.frame.setStyleSheet("QFrame#frame{\n"
"    background-color: qlineargradient(x0:0, y0:1, x2:0, y2:1,stop:0 rgb(113, 109, 252), stop:1 rgb(164, 124, 255));\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMaximumSize(QtCore.QSize(159, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setMinimumSize(QtCore.QSize(12, 12))
        self.pushButton_5.setMaximumSize(QtCore.QSize(12, 12))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(240, 108, 96);\n"
"border:1px solid rgba(113, 17, 15,50);\n"
"border-radius:6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(139, 29, 31)\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setMinimumSize(QtCore.QSize(12, 12))
        self.pushButton_6.setMaximumSize(QtCore.QSize(12, 12))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(227, 199, 0);\n"
"border:1px solid rgba(113, 17, 15,50);\n"
"border-radius:6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(139, 29, 31)\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_7.setMinimumSize(QtCore.QSize(12, 12))
        self.pushButton_7.setMaximumSize(QtCore.QSize(12, 12))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(4, 180, 0);\n"
"border:1px solid rgba(113, 17, 15,50);\n"
"border-radius:6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color:rgb(139, 29, 31)\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(232, 59, 35);\n"
"}\n"
"")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_hudu = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.pushButton_hudu.setFont(font)
        self.pushButton_hudu.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/source/hudu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_hudu.setIcon(icon1)
        self.pushButton_hudu.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_hudu.setObjectName("pushButton_hudu")
        self.verticalLayout_2.addWidget(self.pushButton_hudu)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.pushButton_jiemian = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.pushButton_jiemian.setFont(font)
        self.pushButton_jiemian.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/source/jiemian.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_jiemian.setIcon(icon2)
        self.pushButton_jiemian.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_jiemian.setObjectName("pushButton_jiemian")
        self.verticalLayout_2.addWidget(self.pushButton_jiemian)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.pushButton_xiaoguo = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.pushButton_xiaoguo.setFont(font)
        self.pushButton_xiaoguo.setStyleSheet("QPushButton{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/source/xiaoguo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_xiaoguo.setIcon(icon3)
        self.pushButton_xiaoguo.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_xiaoguo.setObjectName("pushButton_xiaoguo")
        self.verticalLayout_2.addWidget(self.pushButton_xiaoguo)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.pushButton_zong = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.pushButton_zong.setFont(font)
        self.pushButton_zong.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/source/zong.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_zong.setIcon(icon4)
        self.pushButton_zong.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_zong.setObjectName("pushButton_zong")
        self.verticalLayout_2.addWidget(self.pushButton_zong)
        self.verticalLayout.addWidget(self.frame_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_meridional = QtWidgets.QPushButton(self.frame)
        self.pushButton_meridional.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton_meridional.setFont(font)
        self.pushButton_meridional.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_meridional.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(48, 115, 173);\n"
"    border-radius:1px;\n"
"}\n"
"#pushButton_optimize:hover{\n"
"\n"
"    background-color: rgba(48, 115, 173, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#pushButton_optimize:pressed{\n"
"    padding-top:5px;\n"
"    padding \n"
"}")
        self.pushButton_meridional.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_meridional.setObjectName("pushButton_meridional")
        self.verticalLayout.addWidget(self.pushButton_meridional)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_optimize = QtWidgets.QPushButton(self.frame)
        self.pushButton_optimize.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton_optimize.setFont(font)
        self.pushButton_optimize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_optimize.setStyleSheet("QPushButton{\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(48, 115, 173);\n"
"    border-radius:1px;\n"
"}\n"
"#pushButton_optimize:hover{\n"
"\n"
"    background-color: rgba(48, 115, 173, 200);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#pushButton_optimize:pressed{\n"
"    padding-top:5px;\n"
"    padding \n"
"}")
        self.pushButton_optimize.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_optimize.setObjectName("pushButton_optimize")
        self.verticalLayout.addWidget(self.pushButton_optimize)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.verticalLayout.setStretch(1, 4)
        self.verticalLayout.setStretch(2, 3)
        self.horizontalLayout_17.addWidget(self.frame)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setMaximumSize(QtCore.QSize(919, 76))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setStyleSheet("\n"
"QFrame#frame_7{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(162, 129, 247),  stop:1 rgb(119, 111, 252));\n"
"border: 1px outset rgb(98, 91, 213);\n"
"}\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setStyleSheet("border:none")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_undo = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_undo.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_undo.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.pushButton_undo.setFont(font)
        self.pushButton_undo.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/source/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_undo.setIcon(icon5)
        self.pushButton_undo.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_undo.setObjectName("pushButton_undo")
        self.horizontalLayout_6.addWidget(self.pushButton_undo)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.line_2 = QtWidgets.QFrame(self.frame_7)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_2.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 4)
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.frame_19 = QtWidgets.QFrame(self.frame_4)
        self.frame_19.setStyleSheet("QFrame#frame_19{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(66, 226, 192),  stop:1 rgb(62, 154, 193));\n"
"border: 1px outset rgb(72, 158, 204)\n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setStyleSheet("border:none")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_number = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_number.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_number.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.pushButton_number.setFont(font)
        self.pushButton_number.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/source/number.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_number.setIcon(icon6)
        self.pushButton_number.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_number.setObjectName("pushButton_number")
        self.horizontalLayout_9.addWidget(self.pushButton_number)
        self.verticalLayout_11.addWidget(self.frame_20)
        self.line_6 = QtWidgets.QFrame(self.frame_19)
        self.line_6.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_6.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_11.addWidget(self.line_6)
        self.verticalLayout_11.setStretch(1, 4)
        self.horizontalLayout_2.addWidget(self.frame_19)
        self.frame_13 = QtWidgets.QFrame(self.frame_4)
        self.frame_13.setStyleSheet("\n"
"\n"
"QFrame#frame_13{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(253, 139, 133),  stop:1 rgb(248, 194, 152));\n"
"border: 1px outset rgb(252, 194, 149)\n"
"}\n"
"\n"
"")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setStyleSheet("border:none")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_remake = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_remake.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_remake.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.pushButton_remake.setFont(font)
        self.pushButton_remake.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/source/remake.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_remake.setIcon(icon7)
        self.pushButton_remake.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_remake.setObjectName("pushButton_remake")
        self.horizontalLayout_7.addWidget(self.pushButton_remake)
        self.verticalLayout_7.addWidget(self.frame_14)
        self.line_4 = QtWidgets.QFrame(self.frame_13)
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_4.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_7.addWidget(self.line_4)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 4)
        self.horizontalLayout_2.addWidget(self.frame_13)
        self.frame_15 = QtWidgets.QFrame(self.frame_4)
        self.frame_15.setStyleSheet("\n"
"\n"
"\n"
"QFrame#frame_15{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(243, 175, 189),  stop:1 rgb(155, 118, 218));\n"
"border: 1px outset rgb(153, 117, 219)\n"
"}\n"
"\n"
"")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setStyleSheet("border:none")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_output = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_output.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_output.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.pushButton_output.setFont(font)
        self.pushButton_output.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/source/daochu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_output.setIcon(icon8)
        self.pushButton_output.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_output.setObjectName("pushButton_output")
        self.horizontalLayout_10.addWidget(self.pushButton_output)
        self.verticalLayout_8.addWidget(self.frame_16)
        self.line_5 = QtWidgets.QFrame(self.frame_15)
        self.line_5.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_5.setStyleSheet("background-color: rgba(255, 255, 255, 89);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_8.addWidget(self.line_5)
        self.verticalLayout_8.setStretch(0, 1)
        self.verticalLayout_8.setStretch(1, 4)
        self.horizontalLayout_2.addWidget(self.frame_15)
        self.frame_17 = QtWidgets.QFrame(self.frame_4)
        self.frame_17.setStyleSheet("QFrame#frame_17{\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: qradialgradient(cx:0, cy:0, radius:1, fx:0.1, fy:0.1, stop:0 rgb(120, 250, 222),  stop:1 rgb(100, 200, 252));\n"
"border: 1px outset rgb(252, 194, 149)\n"
"}\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_save = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_save.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButton_save.setMaximumSize(QtCore.QSize(41677, 48))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"text-align:left;\n"
"\n"
"    border:0px outset rgb(255, 255, 255);\n"
"    border-radius:8px;\n"
"}\n"
"QPushButton:hover {\n"
"\n"
"border:2px outset rgba(36, 36, 36,0);\n"
"}\n"
"QPushButton:pressed {\n"
"\n"
"border:4px outset rgba(36, 36, 36,0);\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/source/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon9)
        self.pushButton_save.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_11.addWidget(self.pushButton_save)
        self.horizontalLayout_2.addWidget(self.frame_17)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_12.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_resize = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_resize.setMinimumSize(QtCore.QSize(41, 41))
        self.pushButton_resize.setMaximumSize(QtCore.QSize(41, 41))
        self.pushButton_resize.setStyleSheet("border-image: url(:/source/resize.png);\n"
"\n"
"\n"
"")
        self.pushButton_resize.setText("")
        self.pushButton_resize.setObjectName("pushButton_resize")
        self.horizontalLayout_5.addWidget(self.pushButton_resize)
        self.pushButton_control = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_control.setMinimumSize(QtCore.QSize(41, 41))
        self.pushButton_control.setMaximumSize(QtCore.QSize(41, 41))
        self.pushButton_control.setStyleSheet("border-image: url(:/source/control_on.png);")
        self.pushButton_control.setText("")
        self.pushButton_control.setObjectName("pushButton_control")
        self.horizontalLayout_5.addWidget(self.pushButton_control)
        self.pushButton_zhonghu = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_zhonghu.setMinimumSize(QtCore.QSize(41, 41))
        self.pushButton_zhonghu.setMaximumSize(QtCore.QSize(41, 41))
        self.pushButton_zhonghu.setStyleSheet("border-image: url(:/source/zhonghu_on.png);\n"
"")
        self.pushButton_zhonghu.setText("")
        self.pushButton_zhonghu.setObjectName("pushButton_zhonghu")
        self.horizontalLayout_5.addWidget(self.pushButton_zhonghu)
        self.pushButton_drag = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_drag.setMinimumSize(QtCore.QSize(41, 41))
        self.pushButton_drag.setMaximumSize(QtCore.QSize(41, 41))
        self.pushButton_drag.setStyleSheet("border-image: url(:/source/drag_on.png);")
        self.pushButton_drag.setText("")
        self.pushButton_drag.setObjectName("pushButton_drag")
        self.horizontalLayout_5.addWidget(self.pushButton_drag)
        self.pushButton_square = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_square.setMinimumSize(QtCore.QSize(41, 41))
        self.pushButton_square.setMaximumSize(QtCore.QSize(41, 41))
        self.pushButton_square.setStyleSheet("border-image: url(:/source/lashen_off.png);\n"
"")
        self.pushButton_square.setText("")
        self.pushButton_square.setObjectName("pushButton_square")
        self.horizontalLayout_5.addWidget(self.pushButton_square)
        self.pushButton_thick = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_thick.setMinimumSize(QtCore.QSize(41, 41))
        self.pushButton_thick.setMaximumSize(QtCore.QSize(41, 41))
        self.pushButton_thick.setStyleSheet("border-image: url(:/source/cascade_thickness.png);\n"
"\n"
"")
        self.pushButton_thick.setText("")
        self.pushButton_thick.setObjectName("pushButton_thick")
        self.horizontalLayout_5.addWidget(self.pushButton_thick)
        self.pushButton_plot3d = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_plot3d.setMinimumSize(QtCore.QSize(41, 41))
        self.pushButton_plot3d.setMaximumSize(QtCore.QSize(41, 41))
        self.pushButton_plot3d.setStyleSheet("border-image: url(:/source/xyz.png);")
        self.pushButton_plot3d.setText("")
        self.pushButton_plot3d.setObjectName("pushButton_plot3d")
        self.horizontalLayout_5.addWidget(self.pushButton_plot3d)
        self.pushButton_alter = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_alter.setMinimumSize(QtCore.QSize(41, 41))
        self.pushButton_alter.setMaximumSize(QtCore.QSize(41, 41))
        self.pushButton_alter.setStyleSheet("border-image: url(:/source/optimize.png);")
        self.pushButton_alter.setText("")
        self.pushButton_alter.setIconSize(QtCore.QSize(10, 10))
        self.pushButton_alter.setDefault(True)
        self.pushButton_alter.setObjectName("pushButton_alter")
        self.horizontalLayout_5.addWidget(self.pushButton_alter)
        self.pushButton_about = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_about.setMinimumSize(QtCore.QSize(41, 41))
        self.pushButton_about.setMaximumSize(QtCore.QSize(41, 41))
        self.pushButton_about.setStyleSheet("border-image: url(:/source/information.png);\n"
"")
        self.pushButton_about.setText("")
        self.pushButton_about.setObjectName("pushButton_about")
        self.horizontalLayout_5.addWidget(self.pushButton_about)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.comboBox_leixing = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_leixing.setObjectName("comboBox_leixing")
        self.comboBox_leixing.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_leixing)
        self.line = QtWidgets.QFrame(self.frame_6)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.comboBox_jishu = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_jishu.setObjectName("comboBox_jishu")
        self.comboBox_jishu.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_jishu)
        self.line_3 = QtWidgets.QFrame(self.frame_6)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_5.addWidget(self.line_3)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBox_jisuanzhan = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_jisuanzhan.setObjectName("comboBox_jisuanzhan")
        self.comboBox_jisuanzhan.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_jisuanzhan)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout_12.addWidget(self.frame_6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.camber = QtWidgets.QGroupBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camber.sizePolicy().hasHeightForWidth())
        self.camber.setSizePolicy(sizePolicy)
        self.camber.setMinimumSize(QtCore.QSize(100, 100))
        self.camber.setObjectName("camber")
        self.gridLayout.addWidget(self.camber, 0, 0, 1, 1)
        self.sanwei = QtWidgets.QGroupBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sanwei.sizePolicy().hasHeightForWidth())
        self.sanwei.setSizePolicy(sizePolicy)
        self.sanwei.setMinimumSize(QtCore.QSize(100, 100))
        self.sanwei.setObjectName("sanwei")
        self.gridLayout.addWidget(self.sanwei, 0, 1, 1, 1)
        self.yexing = QtWidgets.QGroupBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yexing.sizePolicy().hasHeightForWidth())
        self.yexing.setSizePolicy(sizePolicy)
        self.yexing.setMinimumSize(QtCore.QSize(100, 100))
        self.yexing.setObjectName("yexing")
        self.gridLayout.addWidget(self.yexing, 1, 0, 1, 1)
        self.hubshroud = QtWidgets.QGroupBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hubshroud.sizePolicy().hasHeightForWidth())
        self.hubshroud.setSizePolicy(sizePolicy)
        self.hubshroud.setMinimumSize(QtCore.QSize(100, 100))
        self.hubshroud.setObjectName("hubshroud")
        self.gridLayout.addWidget(self.hubshroud, 1, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout)
        self.info = QtWidgets.QTextBrowser(self.frame_5)
        self.info.setMinimumSize(QtCore.QSize(0, 50))
        self.info.setMaximumSize(QtCore.QSize(16777215, 50))
        self.info.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.info.setObjectName("info")
        self.verticalLayout_12.addWidget(self.info)
        self.horizontalLayout_17.addWidget(self.frame_5)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_17)
        sCO2blade_designer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sCO2blade_designer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 26))
        self.menubar.setObjectName("menubar")
        sCO2blade_designer.setMenuBar(self.menubar)

        self.retranslateUi(sCO2blade_designer)
        QtCore.QMetaObject.connectSlotsByName(sCO2blade_designer)

    def retranslateUi(self, sCO2blade_designer):
        _translate = QtCore.QCoreApplication.translate
        sCO2blade_designer.setWindowTitle(_translate("sCO2blade_designer", "HTDO V1.0"))
        self.pushButton_hudu.setText(_translate("sCO2blade_designer", "弧度曲线"))
        self.pushButton_jiemian.setText(_translate("sCO2blade_designer", "截面图"))
        self.pushButton_xiaoguo.setText(_translate("sCO2blade_designer", "效果图"))
        self.pushButton_zong.setText(_translate("sCO2blade_designer", "总视图"))
        self.pushButton_meridional.setText(_translate("sCO2blade_designer", "透平子午线"))
        self.pushButton_optimize.setText(_translate("sCO2blade_designer", "优化计算"))
        self.pushButton_undo.setText(_translate("sCO2blade_designer", "撤销操作"))
        self.pushButton_number.setText(_translate("sCO2blade_designer", "显示参数"))
        self.pushButton_remake.setText(_translate("sCO2blade_designer", "重新绘制"))
        self.pushButton_output.setText(_translate("sCO2blade_designer", "导出文件"))
        self.pushButton_save.setText(_translate("sCO2blade_designer", "保存文件"))
        self.label_3.setText(_translate("sCO2blade_designer", "类型"))
        self.comboBox_leixing.setItemText(0, _translate("sCO2blade_designer", "静叶"))
        self.label_4.setText(_translate("sCO2blade_designer", "级数"))
        self.comboBox_jishu.setItemText(0, _translate("sCO2blade_designer", "1"))
        self.label_5.setText(_translate("sCO2blade_designer", "计算站"))
        self.comboBox_jisuanzhan.setItemText(0, _translate("sCO2blade_designer", "1"))
        self.camber.setTitle(_translate("sCO2blade_designer", "弧度曲线"))
        self.sanwei.setTitle(_translate("sCO2blade_designer", "三维"))
        self.yexing.setTitle(_translate("sCO2blade_designer", "截面"))
        self.hubshroud.setTitle(_translate("sCO2blade_designer", "叶根叶顶曲线"))
import ui.source.pic_rc
